modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/magma-core/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/MagmaCore_NEO.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/magma-core"
itemIcon="minecraft:magma"
logoFile="logo.png"
#credits=""
authors="${mod_authors}"
description='''This is the core mod that is needed for the other RexRaptor mods!'''

[modproperties.${mod_id}]
configuredBackground="minecraft:textures/block/magma.png"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
mandatory=true
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jei"
type="optional"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="roughlyenoughitems"
type="optional"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="emi"
type="optional"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="BOTH"
